name: Deploy Project

on:
    push:
        branches:
            - deploy

jobs:
    deploy:
        runs-on: ubuntu-latest

        env:
            PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
            HOST_IP: ${{ secrets.HOST_IP }}
            HOST_USERNAME: ${{ secrets.HOST_USERNAME }}
            PROJECT_PORT: ${{ secrets.PROJECT_PORT }}
            ENV_TEXT: ${{ secrets.ENV_TEXT }}

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18'

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Restore pnpm cache
              uses: pnpm/action-setup@v2
              with:
                  version: 'latest'

            - name: Create .env file
              run: echo "${{ env.ENV_TEXT }}" > .env

            - name: Install dependencies and build
              run: |
                  pnpm install
                  pnpm build

            - name: Build Docker Image
              run: docker build -t ${{ env.PROJECT_NAME }} .

            - name: Save Docker image as tar
              run: docker save ${{ env.PROJECT_NAME }} -o ${PROJECT_NAME}.tar

            - name: Load Docker image, remove old image, and run container on remote server
              uses: appleboy/ssh-action@v0.1.8
              with:
                  host: ${{ secrets.HOST_IP }}
                  username: ${{ secrets.HOST_USERNAME }}
                  key: ${{ secrets.PEM_KEY }}
                  port: 22
                  script: |
                      scp -o StrictHostKeyChecking=no ${PROJECT_NAME}.tar ${{ secrets.HOST_USERNAME }}@${{ secrets.HOST_IP }}:/home/${{ env.PROJECT_NAME }}/${PROJECT_NAME}.tar

                      cd /home/${{ env.PROJECT_NAME }}
                      if [ ! -f ${PROJECT_NAME}.tar ]; then
                        echo "Docker image file not found!"
                        exit 1
                      fi

                      old_image=$(docker images -q ${{ env.PROJECT_NAME }}:latest)
                      if [ -n "$old_image" ]; then
                        docker rmi -f $old_image
                      fi

                      docker load -i ${PROJECT_NAME}.tar

                      docker-compose down
                      PROJECT_NAME=${{ env.PROJECT_NAME }} PROJECT_PORT=${{ env.PROJECT_PORT }} docker-compose up -d

            - name: Cleanup local Docker image tar
              run: rm ${PROJECT_NAME}.tar
